/*
 * Embedded ElyraSQL — C ABI.
 *
 * MySQL-compatible SQL over a single file, in your own process: no server, no
 * socket, no wire protocol. A file written here is the same file `elyrasql
 * serve` reads, and the SQL semantics are identical because it is the same
 * engine.
 *
 * Conventions
 * -----------
 *   * Fallible calls return ELYRA_OK or ELYRA_ERR; on ELYRA_ERR, call
 *     elyra_last_error() for a message (thread-local, valid until the next
 *     failing call on that thread).
 *   * Handles are opaque and owned by the caller. Each has a matching *_free,
 *     and freeing NULL is a no-op.
 *   * Strings returned by this API borrow from the handle they came from and
 *     stay valid until it is freed. Never free them yourself.
 *   * A panic can never cross this boundary: the entry points abort instead.
 *
 * Threads
 * -------
 *   A database and its connections may be used from several threads, but one
 *   connection carries session state and must not be shared between threads.
 *   Give each thread its own connection.
 *
 * Linking
 * -------
 *   cargo build -p elyra-embed-capi --release
 *   cc app.c -I crates/elyra-embed-capi/include \
 *            -L target/release -lelyrasql -o app
 */

#ifndef ELYRASQL_H
#define ELYRASQL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ELYRA_OK 0
#define ELYRA_ERR (-1)

typedef struct ElyraDb ElyraDb;
typedef struct ElyraConn ElyraConn;
typedef struct ElyraRows ElyraRows;

/* Diagnostics -------------------------------------------------------------- */

/* Message for the last failing call on this thread, or NULL after a success. */
const char *elyra_last_error(void);

/* The ElyraSQL version this library was built from. Static; never freed. */
const char *elyra_version(void);

/* Database ----------------------------------------------------------------- */

/* Open, creating the file if it does not exist. */
int elyra_db_open(const char *path, ElyraDb **out);

/* Open a throwaway database; its file is deleted by elyra_db_free. */
int elyra_db_open_temporary(ElyraDb **out);

/* As elyra_db_open, with a bound on the runtime's worker threads. */
int elyra_db_open_with_threads(const char *path, size_t worker_threads, ElyraDb **out);

/* The database file's path; valid until the handle is freed. */
const char *elyra_db_path(const ElyraDb *db);

/* Release the handle. For a temporary database, deletes the file. */
void elyra_db_free(ElyraDb *db);

/* Connection --------------------------------------------------------------- */

/* Open a session. It may outlive the ElyraDb handle it came from. */
int elyra_db_connect(const ElyraDb *db, ElyraConn **out);

void elyra_conn_free(ElyraConn *conn);

/*
 * Run one or more ';'-separated statements. affected_out may be NULL;
 * otherwise it receives the total number of rows changed.
 */
int elyra_conn_execute(const ElyraConn *conn, const char *sql, uint64_t *affected_out);

/* Run one statement and collect its result set into *out. */
int elyra_conn_query(const ElyraConn *conn, const char *sql, ElyraRows **out);

/* The id generated by this session's last INSERT. */
int64_t elyra_conn_last_insert_id(const ElyraConn *conn);

/* Result sets -------------------------------------------------------------- */

size_t elyra_rows_count(const ElyraRows *rows);
size_t elyra_rows_columns(const ElyraRows *rows);

/* Column name, or NULL when col is out of range. */
const char *elyra_rows_column_name(const ElyraRows *rows, size_t col);

/*
 * One value in its MySQL text form, borrowed from rows. NULL is returned both
 * for SQL NULL and for an out-of-range index; elyra_rows_is_null distinguishes
 * them.
 */
const char *elyra_rows_value(const ElyraRows *rows, size_t row, size_t col);

/* 1 = SQL NULL, 0 = not NULL, -1 = out of range. */
int elyra_rows_is_null(const ElyraRows *rows, size_t row, size_t col);

void elyra_rows_free(ElyraRows *rows);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ELYRASQL_H */
